spring.application.name=etecfer

# Configuração do Banco de Dados

spring.datasource.url=jdbc:postgresql://localhost:5432/etecfer_db
spring.datasource.username=postgres
spring.datasource.password=postdba

# Atualizar as tabelas do Banco de Dados automaticamente
spring.jpa.hibernate.ddl-auto=update

# Não formatar  os comandos SQL no console
spring.jpa.properties.hibernate.format_sql=false

# Mostrar os comandos SQL no console
spring.jpa.show-sql=true

# Configurar a porta so servidor
server.port=8080
